apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: reports
spec:
  selector:
    matchLabels:
      app: reports
  replicas: 1
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
      - name: master
        image: us-west3-docker.pkg.dev/plagiarim-checker/plagiarism-checker-artifact/reports
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: credentials
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi